import type {Metadata} from "next";
import {Geist, Geist_Mono, Poppins} from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/providers/session-provider";
import {ThemeProvider} from "@/providers/theme-provider";
import {Toaster} from "@/components/ui/sonner";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'], // Add the weights you need
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${poppins.className} ${poppins.className} antialiased`}
        >
        <NextAuthProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                {children}
                <Toaster />
            </ThemeProvider>
        </NextAuthProvider>
        </body>
        </html>
    );
}
